services:
  web:
    build:
      context: .
      dockerfile: ./final_web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.btfptkpngrtnnqweftvx:LNQKhanh1509@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

