# Generated by Django 4.2.6 on 2024-09-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_text_color_text_duration_text_font_text_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='height',
        ),
        migrations.RemoveField(
            model_name='text',
            name='width',
        ),
        migrations.AddField(
            model_name='text',
            name='fontsize',
            field=models.IntegerField(default=100),
        ),
    ]
