# Generated by Django 4.2.6 on 2024-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_text_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
