# Generated by Django 4.2.6 on 2024-09-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.URLField(default='https://btfptkpngrtnnqweftvx.supabase.co/storage/v1/object/public/audio_files/image/oweiIPFVGAAIVCmcAIV4eAaK5FeGcLQe5AqzJ1.jpeg', max_length=500),
        ),
        migrations.AddField(
            model_name='effect',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='image',
            field=models.URLField(default='https://btfptkpngrtnnqweftvx.supabase.co/storage/v1/object/public/audio_files/image/oweiIPFVGAAIVCmcAIV4eAaK5FeGcLQe5AqzJ1.jpeg', max_length=500),
        ),
        migrations.AddField(
            model_name='filter',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='image',
            field=models.URLField(default='https://btfptkpngrtnnqweftvx.supabase.co/storage/v1/object/public/audio_files/image/oweiIPFVGAAIVCmcAIV4eAaK5FeGcLQe5AqzJ1.jpeg', max_length=500),
        ),
        migrations.AddField(
            model_name='sticker',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.URLField(default='https://btfptkpngrtnnqweftvx.supabase.co/storage/v1/object/public/audio_files/image/oweiIPFVGAAIVCmcAIV4eAaK5FeGcLQe5AqzJ1.jpeg', max_length=500),
        ),
        migrations.AddField(
            model_name='text',
            name='image',
            field=models.URLField(default='https://btfptkpngrtnnqweftvx.supabase.co/storage/v1/object/public/audio_files/image/oweiIPFVGAAIVCmcAIV4eAaK5FeGcLQe5AqzJ1.jpeg', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
