# Generated by Django 4.2.6 on 2024-09-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_audio_image_effect_duration_effect_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsession',
            name='video',
        ),
        migrations.AddField(
            model_name='editsession',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='editsession',
            name='actions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
