# Generated by Django 4.2.6 on 2024-09-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_editsession_video_editsession_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text_file',
        ),
    ]
