# Generated by Django 4.2.6 on 2024-09-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_text_text_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectConfigSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('blur', 'Blur'), ('zoom', 'Zoom'), ('brightness', 'Brightness')], max_length=50, unique=True)),
                ('config_schema', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='effect',
            name='effect_file',
        ),
        migrations.AddField(
            model_name='effect',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='effectConfigSchema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.effectconfigschema'),
            preserve_default=False,
        ),
    ]
