# Generated by Django 4.2.6 on 2024-09-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_effectconfigschema_remove_effect_effect_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='effectConfigSchema',
        ),
        migrations.DeleteModel(
            name='EffectConfigSchema',
        ),
    ]
