# Generated by Django 4.2.6 on 2024-09-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_effect_effectconfigschema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('trending', 'Trending'), ('nightclub', 'Nightclub'), ('lens', 'Lens'), ('retro', 'Retro'), ('tv', 'TV'), ('star', 'Star'), ('trending_body', 'Trending Body'), ('mood_body', 'Mood Body'), ('mask_body', 'Mask Body'), ('selfie_body', 'Selfie Body')], max_length=50),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category',
            field=models.CharField(choices=[('featured', 'Featured'), ('life', 'Life'), ('scenery', 'Scenery'), ('movies', 'Movies'), ('retro', 'Retro'), ('style', 'Style')], max_length=50),
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.CharField(choices=[('default', 'Default'), ('trending', 'Trending'), ('basic', 'Basic'), ('multicolor', 'Multicolor')], max_length=50),
        ),
    ]
