# Generated by Django 4.2.6 on 2024-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_effect_category_alter_filter_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='color',
        ),
        migrations.RemoveField(
            model_name='text',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='text',
            name='font',
        ),
        migrations.RemoveField(
            model_name='text',
            name='fontsize',
        ),
        migrations.RemoveField(
            model_name='text',
            name='stroke_color',
        ),
        migrations.RemoveField(
            model_name='text',
            name='stroke_width',
        ),
        migrations.AddField(
            model_name='text',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
