# Generated by Django 4.2.6 on 2024-09-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_text_color_remove_text_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='image',
        ),
    ]
