# Generated by Django 4.2.6 on 2024-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_sticker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='filter_file',
        ),
        migrations.AddField(
            model_name='filter',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
