# Generated by Django 4.2.6 on 2024-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_filter_filter_file_filter_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='intensity',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
