# Generated by Django 4.2.6 on 2024-09-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_filter_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='duration',
        ),
    ]
