# Generated by Django 4.2.6 on 2024-09-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_filter_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
