# Generated by Django 4.2.6 on 2024-10-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_text_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(default='https://btfptkpngrtnnqweftvx.supabase.co/storage/v1/object/public/user_image/images.png', max_length=500),
        ),
    ]
