# Generated by Django 4.2.6 on 2024-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Lê Nguyễn Quốc Khánh', max_length=255),
        ),
    ]
