# Generated by Django 5.1.3 on 2024-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='text',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
