# Generated by Django 5.1.3 on 2024-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_text_is_valid_text_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='text',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
