# Generated by Django 5.1.3 on 2024-12-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_text_is_valid_remove_text_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
